[project]
name = "django-portfolio"
version = "0.1.0"
description = ""
authors = [
    {name = "NoFate35",email = "vsokol35@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tzdata (>=2026.3,<2027.0)",
    "django (>=6.1.1,<7.0.0)",
    "dj-database-url (>=3.1.2,<4.0.0)",
    "dotenv (>=0.9.9,<0.10.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
